services:
  db:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: rootPassword
      MYSQL_USER: ansUser
      MYSQL_PASSWORD: ansPassword
      MYSQL_DATABASE: ansDb
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
